name: 'Output String'
description: 'Outputs a string'
inputs:
  input-string:  # id of input
    description: 'what is the string to output'
    required: true
    default: 'defaultString'

outputs:
  output-string:
    description: 'The output string'

runs:
  using: "composite"
  steps:
    - run: echo "::set-output name=output-string::${{ inputs.input-string }}"
      shell: bash