name: 'Output String'
description: 'Outputs a string'
inputs:
  input-string:  # id of input
    description: 'what is the string to output'
    required: true
    default: 'defaultString'

outputs:
  string-output:
    description: 'The output string'
    value: ${{ inputs.input-string }}

runs:
  using: "composite"
  steps:

    - name: Debug Input
      run: echo "Input Value: ${{ inputs.input-string }}"
      shell: bash

    - name: Set Output
    - run: echo "::set-output name=string-output::${{ inputs.input-string }}"
      shell: bash