  name: 'Output String'
  description: 'Outputs a string'
  inputs:
    input-string:  # id of input
      description: 'what is the string to output'
      required: true
      default: 'defaultString'
  outputs:
    string-output:
      description: 'The output string'

  runs:
    using: "composite"
    steps:

      - name: Debug Output
        run: echo "${{ inputs.input-string }}"
        shell: bash

      - id: output-string
        run: echo "::set-output name=string-output::${{ inputs.input-string }}"
        shell: bash

      - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
        shell: bash

      - name: Save Output to File
        run: echo "${{ steps.output-string.outputs.string-output }}" > ~/Desktop/bootcamp-dir1/artifact/string.txt
        shell: bash