name: 'Output String'
description: 'Outputs a string'
inputs:
  input-string:  # id of input
    description: 'what is the string to output'
    required: true
    default: 'defaultString'
outputs:
  string-output:
    description: 'The output string'
    value: ${{ steps.output-string.outputs.string-output }}

runs:
  using: "composite"
  steps:

    - id: output-string
    - run: echo "::set-output name=string-output::${{ inputs.input-string }}"
      shell: bash

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash