name: 'Output String'
description: 'Outputs a string'
inputs:
  input-string:  # id of input
    description: 'what is the string to output'
    required: true
    default: 'defaultString'

runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.input-string }}.
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash