  name: 'Output String'
  description: 'Outputs a string'
  inputs:
    input-string:  # id of input
      description: 'what is the string to output'
      required: true
      default: 'defaultString'

  outputs:
    string-output:
      description: 'The output string'

  runs:
    using: "composite"
    steps:  

      - id: output-string
        run: echo "${{ inputs.input-string }}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Save Output to File
        run: echo "${{ inputs.input-string }}" > ~/Desktop/bootcamp-dir1/artifact/string.txt
        shell: bash